#!/bin/bash

sudo apt-get install -y python3-dev
sudo apt-get install -y python3-affine
sudo apt-get install -y python3-agate
sudo apt-get install -y python3-aiofiles
sudo apt-get install -y python3-aiohttp
sudo apt-get install -y python3-aiosignal
sudo apt-get install -y python3-aiosqlite
sudo apt-get install -y python3-alabaster
sudo apt-get install -y python3-alembic
sudo apt-get install -y python3-anyio
sudo apt-get install -y python3-appdirs
sudo apt-get install -y python3-apptools
sudo apt-get install -y python3-argcomplete
sudo apt-get install -y python3-arrow
sudo apt-get install -y python3-astroid
sudo apt-get install -y python3-astropy
sudo apt-get install -y python3-asttokens
sudo apt-get install -y python3-async-timeout
sudo apt-get install -y python3-asyncpg
sudo apt-get install -y python3-atomicwrites
sudo apt-get install -y python3-automat
sudo apt-get install -y python3-autopep8
sudo apt-get install -y python3-babel
sudo apt-get install -y python3-backcall
sudo apt-get install -y python3-bcrypt
sudo apt-get install -y python3-binaryornot
sudo apt-get install -y python3-biopython
sudo apt-get install -y python3-bleach
sudo apt-get install -y python3-blosc
sudo apt-get install -y python3-boto3
sudo apt-get install -y python3-botocore
sudo apt-get install -y python3-bottleneck
sudo apt-get install -y python3-brotli
sudo apt-get install -y python3-btrees
sudo apt-get install -y python3-cachecontrol
sudo apt-get install -y python3-cached-property
sudo apt-get install -y python3-cartopy
sudo apt-get install -y python3-certifi
sudo apt-get install -y python3-cffi
sudo apt-get install -y python3-chameleon
sudo apt-get install -y python3-chardet
sudo apt-get install -y python3-charset-normalizer
sudo apt-get install -y python3-click
sudo apt-get install -y python3-click-plugins
sudo apt-get install -y python3-cligj
sudo apt-get install -y python3-cloudpickle
sudo apt-get install -y python3-colorama
sudo apt-get install -y python3-colorcet
sudo apt-get install -y python3-configargparse
sudo apt-get install -y python3-configobj
sudo apt-get install -y python3-constantly
sudo apt-get install -y python3-contextlib2
sudo apt-get install -y python3-cookiecutter
sudo apt-get install -y python3-coverage
sudo apt-get install -y python3-cryptography
sudo apt-get install -y python3-cssselect
sudo apt-get install -y python3-csvkit
sudo apt-get install -y python3-cvxopt
sudo apt-get install -y python3-cycler
sudo apt-get install -y python3-cytoolz
sudo apt-get install -y python3-dask
sudo apt-get install -y python3-datrie
sudo apt-get install -y python3-dbf
sudo apt-get install -y python3-dbus
sudo apt-get install -y python3-decorator
sudo apt-get install -y python3-defusedxml
sudo apt-get install -y python3-diff-match-patch
sudo apt-get install -y python3-dill
sudo apt-get install -y python3-distlib
sudo apt-get install -y python3-distributed
sudo apt-get install -y python3-django
sudo apt-get install -y python3-dnspython
sudo apt-get install -y python3-docopt
sudo apt-get install -y python3-docutils
sudo apt-get install -y python3-dropbox
sudo apt-get install -y python3-ecdsa
sudo apt-get install -y python3-elasticsearch
sudo apt-get install -y python3-entrypoints
sudo apt-get install -y python3-envisage
sudo apt-get install -y python3-ephem
sudo apt-get install -y python3-executing
sudo apt-get install -y python3-feedparser
sudo apt-get install -y python3-filelock
sudo apt-get install -y python3-fiona
sudo apt-get install -y python3-flake8
sudo apt-get install -y python3-flask
sudo apt-get install -y python3-flask-cors
sudo apt-get install -y python3-flask-login
sudo apt-get install -y python3-flask-socketio
sudo apt-get install -y python3-fonttools
sudo apt-get install -y python3-freetype
sudo apt-get install -y python3-frozenlist
sudo apt-get install -y python3-fsspec
sudo apt-get install -y python3-furl
sudo apt-get install -y python3-future
sudo apt-get install -y python3-gdal
sudo apt-get install -y python3-gevent-websocket
sudo apt-get install -y python3-gflags
sudo apt-get install -y python3-git
sudo apt-get install -y python3-gmpy2
sudo apt-get install -y python3-graphviz
sudo apt-get install -y python3-greenlet
sudo apt-get install -y python3-gunicorn
sudo apt-get install -y python3-h5py
sudo apt-get install -y python3-hdf4
sudo apt-get install -y python3-heapdict
sudo apt-get install -y python3-html5lib
sudo apt-get install -y python3-humanize
sudo apt-get install -y python3-hyperlink
sudo apt-get install -y python3-hypothesis
sudo apt-get install -y python3-icu
sudo apt-get install -y python3-idna
sudo apt-get install -y python3-imageio
sudo apt-get install -y python3-imagesize
sudo apt-get install -y python3-importlib-metadata
sudo apt-get install -y python3-incremental
sudo apt-get install -y python3-inflection
sudo apt-get install -y python3-iniconfig
sudo apt-get install -y python3-intake
sudo apt-get install -y python3-intervaltree
sudo apt-get install -y python3-ipykernel
sudo apt-get install -y python3-ipyparallel
sudo apt-get install -y python3-ipython
sudo apt-get install -y python3-ipywidgets
sudo apt-get install -y python3-iso8601
sudo apt-get install -y python3-isort
sudo apt-get install -y python3-itemadapter
sudo apt-get install -y python3-itemloaders
sudo apt-get install -y python3-itsdangerous
sudo apt-get install -y python3-jaraco.classes
sudo apt-get install -y python3-jedi
sudo apt-get install -y python3-jeepney
sudo apt-get install -y python3-jellyfish
sudo apt-get install -y python3-jinja2
sudo apt-get install -y python3-jinja2-time
sudo apt-get install -y python3-jmespath
sudo apt-get install -y python3-joblib
sudo apt-get install -y python3-json5
sudo apt-get install -y python3-jsonschema
sudo apt-get install -y python3-keyring
sudo apt-get install -y python3-kiwisolver
sudo apt-get install -y python3-lazy-object-proxy
sudo apt-get install -y python3-ldap3
sudo apt-get install -y python3-lerc
sudo apt-get install -y python3-libtiff
sudo apt-get install -y python3-libxml2
sudo apt-get install -y python3-llvmlite
sudo apt-get install -y python3-locket
sudo apt-get install -y python3-lockfile
sudo apt-get install -y python3-lxml
sudo apt-get install -y python3-lz4
sudo apt-get install -y python3-lzo
sudo apt-get install -y python3-mako
sudo apt-get install -y python3-markdown
sudo apt-get install -y python3-markdown2
sudo apt-get install -y python3-markupsafe
sudo apt-get install -y python3-matplotlib
sudo apt-get install -y python3-matplotlib-inline
sudo apt-get install -y python3-mccabe
sudo apt-get install -y python3-mdit-py-plugins
sudo apt-get install -y python3-mdp
sudo apt-get install -y python3-meld3
sudo apt-get install -y python3-mistune
sudo apt-get install -y python3-mock
sudo apt-get install -y python3-more-itertools
sudo apt-get install -y python3-morfessor
sudo apt-get install -y python3-mpi4py
sudo apt-get install -y python3-mpmath
sudo apt-get install -y python3-multidict
sudo apt-get install -y python3-multipledispatch
sudo apt-get install -y python3-multiprocess
sudo apt-get install -y python3-munch
sudo apt-get install -y python3-munkres
sudo apt-get install -y python3-mypy
sudo apt-get install -y python3-natsort
sudo apt-get install -y python3-nbclassic
sudo apt-get install -y python3-nbclient
sudo apt-get install -y python3-nbconvert
sudo apt-get install -y python3-nbformat
sudo apt-get install -y python3-nest-asyncio
sudo apt-get install -y python3-netcdf4
sudo apt-get install -y python3-networkx
sudo apt-get install -y python3-nltk
sudo apt-get install -y python3-nose-parameterized
sudo apt-get install -y python3-notebook
sudo apt-get install -y python3-nss
sudo apt-get install -y python3-numba
sudo apt-get install -y python3-numexpr
sudo apt-get install -y python3-numpy
sudo apt-get install -y python3-numpydoc
sudo apt-get install -y python3-olefile
sudo apt-get install -y python3-opencv
sudo apt-get install -y python3-openpyxl
sudo apt-get install -y python3-openssl
sudo apt-get install -y python3-opentracing
sudo apt-get install -y python3-packaging
sudo apt-get install -y python3-pandas
sudo apt-get install -y python3-pandocfilters
sudo apt-get install -y python3-param
sudo apt-get install -y python3-paramiko
sudo apt-get install -y python3-parsedatetime
sudo apt-get install -y python3-parsel
sudo apt-get install -y python3-parso
sudo apt-get install -y python3-partd
sudo apt-get install -y python3-passlib
sudo apt-get install -y python3-pathspec
sudo apt-get install -y python3-pathtools
sudo apt-get install -y python3-patsy
sudo apt-get install -y python3-pep8
sudo apt-get install -y python3-pexpect
sudo apt-get install -y python3-pickleshare
sudo apt-get install -y python3-pillow
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-plac
sudo apt-get install -y python3-platformdirs
sudo apt-get install -y python3-plotly
sudo apt-get install -y python3-pluggy
sudo apt-get install -y python3-ply
sudo apt-get install -y python3-pomegranate
sudo apt-get install -y python3-portend
sudo apt-get install -y python3-portpicker
sudo apt-get install -y python3-postgresql
sudo apt-get install -y python3-progress
sudo apt-get install -y python3-prompt-toolkit
sudo apt-get install -y python3-protego
sudo apt-get install -y python3-protobuf
sudo apt-get install -y python3-psutil
sudo apt-get install -y python3-psycopg2
sudo apt-get install -y python3-ptyprocess
sudo apt-get install -y python3-pyasn1
sudo apt-get install -y python3-pyasn1-modules
sudo apt-get install -y python3-pycodestyle
sudo apt-get install -y python3-pycparser
sudo apt-get install -y python3-pyct
sudo apt-get install -y python3-pycurl
sudo apt-get install -y python3-pydocstyle
sudo apt-get install -y python3-pydot
sudo apt-get install -y python3-pydotplus
sudo apt-get install -y python3-pyemd
sudo apt-get install -y python3-pyflakes
sudo apt-get install -y python3-pygments
sudo apt-get install -y python3-pygpu
sudo apt-get install -y python3-pyls-spyder
sudo apt-get install -y python3-pymongo
sudo apt-get install -y python3-pympler
sudo apt-get install -y python3-pymssql
sudo apt-get install -y python3-pymysql
sudo apt-get install -y python3-pyodbc
sudo apt-get install -y python3-pyparsing
sudo apt-get install -y python3-pyproj
sudo apt-get install -y python3-pyqtgraph
sudo apt-get install -y python3-pyquery
sudo apt-get install -y python3-pyrsistent
sudo apt-get install -y python3-pyshp
sudo apt-get install -y python3-pysmi
sudo apt-get install -y python3-pytest
sudo apt-get install -y python3-pytest-arraydiff
sudo apt-get install -y python3-pytest-astropy
sudo apt-get install -y python3-pytest-astropy-header
sudo apt-get install -y python3-pytest-asyncio
sudo apt-get install -y python3-pytest-cov
sudo apt-get install -y python3-pytest-doctestplus
sudo apt-get install -y python3-pytest-mock
sudo apt-get install -y python3-pytest-openfiles
sudo apt-get install -y python3-pytest-pep8
sudo apt-get install -y python3-pytest-remotedata
sudo apt-get install -y python3-pytest-runner
sudo apt-get install -y python3-pytest-timeout
sudo apt-get install -y python3-pytest-xdist
sudo apt-get install -y python3-python-utils
sudo apt-get install -y python3-pyxdg
sudo apt-get install -y python3-qdarkstyle
sudo apt-get install -y python3-qstylizer
sudo apt-get install -y python3-qtawesome
sudo apt-get install -y python3-qtconsole
sudo apt-get install -y python3-qtpy
sudo apt-get install -y python3-queuelib
sudo apt-get install -y python3-rasterio
sudo apt-get install -y python3-redis
sudo apt-get install -y python3-regex
sudo apt-get install -y python3-reportlab
sudo apt-get install -y python3-repoze.lru
sudo apt-get install -y python3-requests
sudo apt-get install -y python3-requests-file
sudo apt-get install -y python3-requests-kerberos
sudo apt-get install -y python3-responses
sudo apt-get install -y python3-rope
sudo apt-get install -y python3-routes
sudo apt-get install -y python3-rtree
sudo apt-get install -y python3-scikit-rf
sudo apt-get install -y python3-scipy
sudo apt-get install -y python3-scrapy
sudo apt-get install -y python3-seaborn
sudo apt-get install -y python3-secretstorage
sudo apt-get install -y python3-send2trash
sudo apt-get install -y python3-setuptools
sudo apt-get install -y python3-sh
sudo apt-get install -y python3-shapely
sudo apt-get install -y python3-simplejson
sudo apt-get install -y python3-sip
sudo apt-get install -y python3-six
sudo apt-get install -y python3-snappy
sudo apt-get install -y python3-sniffio
sudo apt-get install -y python3-snowballstemmer
sudo apt-get install -y python3-snuggs
sudo apt-get install -y python3-sortedcontainers
sudo apt-get install -y python3-soupsieve
sudo apt-get install -y python3-sphinx
sudo apt-get install -y python3-spyder-kernels
sudo apt-get install -y python3-sqlalchemy
sudo apt-get install -y python3-sqlalchemy-utils
sudo apt-get install -y python3-sqlparse
sudo apt-get install -y python3-statsmodels
sudo apt-get install -y python3-streamz
sudo apt-get install -y python3-svn
sudo apt-get install -y python3-sympy
sudo apt-get install -y python3-tabulate
sudo apt-get install -y python3-tblib
sudo apt-get install -y python3-tempita
sudo apt-get install -y python3-tenacity
sudo apt-get install -y python3-termcolor
sudo apt-get install -y python3-terminado
sudo apt-get install -y python3-text-unidecode
sudo apt-get install -y python3-textdistance
sudo apt-get install -y python3-theano
sudo apt-get install -y python3-threadpoolctl
sudo apt-get install -y python3-three-merge
sudo apt-get install -y python3-thrift
sudo apt-get install -y python3-thriftpy
sudo apt-get install -y python3-tifffile
sudo apt-get install -y python3-tinycss2
sudo apt-get install -y python3-tk
sudo apt-get install -y python3-tldextract
sudo apt-get install -y python3-toml
sudo apt-get install -y python3-tomli
sudo apt-get install -y python3-tomlkit
sudo apt-get install -y python3-toolz
sudo apt-get install -y python3-torchvision
sudo apt-get install -y python3-tornado
sudo apt-get install -y python3-tqdm
sudo apt-get install -y python3-traitlets
sudo apt-get install -y python3-traits
sudo apt-get install -y python3-traitsui
sudo apt-get install -y python3-transaction
sudo apt-get install -y python3-translationstring
sudo apt-get install -y python3-twisted
sudo apt-get install -y python3-typing-extensions
sudo apt-get install -y python3-ujson
sudo apt-get install -y python3-unidecode
sudo apt-get install -y python3-urllib3
sudo apt-get install -y python3-uvloop
sudo apt-get install -y python3-vcversioner
sudo apt-get install -y python3-venusian
sudo apt-get install -y python3-virtualenv
sudo apt-get install -y python3-vispy
sudo apt-get install -y python3-w3lib
sudo apt-get install -y python3-waitress
sudo apt-get install -y python3-watchdog
sudo apt-get install -y python3-wcwidth
sudo apt-get install -y python3-webencodings
sudo apt-get install -y python3-webob
sudo apt-get install -y python3-webtest
sudo apt-get install -y python3-werkzeug
sudo apt-get install -y python3-wget
sudo apt-get install -y python3-whatthepatch
sudo apt-get install -y python3-wheel
sudo apt-get install -y python3-whoosh
sudo apt-get install -y python3-widgetsnbextension
sudo apt-get install -y python3-wrapt
sudo apt-get install -y python3-ws4py
sudo apt-get install -y python3-wtforms
sudo apt-get install -y python3-wurlitzer
sudo apt-get install -y python3-xarray
sudo apt-get install -y python3-yaml
sudo apt-get install -y python3-yapf
sudo apt-get install -y python3-yarl
sudo apt-get install -y python3-yt
sudo apt-get install -y python3-zict
sudo apt-get install -y python3-zipp
sudo apt-get install -y python3-zope
sudo apt-get install -y python3-zope.deprecation
sudo apt-get install -y python3-zope.interface
sudo apt-get install -y python3-zstd
